### PR TITLE
Add CodexCoin Event Listeners / Socket Notifications

### PR DESCRIPTION
**Pull request by Anaphase**
This PR adds support for handling CodexCoin-based socket events.

[See the corresponding back-end PR here.](https://github.com/codex-protocol/service.codex-registry-api/pull/10)

### CODE REVIEW

**Comment by Anaphase** [comment]
I see the advantages of both, but I think I favor listening for events through the API for the reason you stated above. I'm also okay with just listening for events on the frontend, but that has it's own challenges (e.g. what happens if someone refreshes after you register a listener for a tx hash? or are you going to process contract events block by block?)

FWIW, I suppose this is a slightly more "centralized" approach, but the frontend isn't actually reading data from the API for CodexCoin events. The API just sends a notification to the frontend when it knows a transaction has been mined after N confirmations, then the frontend queries the contract for new data directly via web3.

In any case, this PR was really just to quickly get CodexCoin notifications / reactivity up an running since we've got our hands pretty full at the moment.

**Comment by sprice** [comment]
This may be a comment for both this PR and the API PR.

When I approve the registry contract, the UI optimistically says that it has been approved, even while the modal is showing. A few seconds later I receive the new notification flash message. As soon as this happens, the UI updates to say that the registry contract is not approved. Refreshing the page tells me the contract is not approved.

**Comment by sprice** [comment]
The same thing happens with receiving from the faucet. It optimistically updates balance. Then i receive the flash message saying I have received the tokens, but it reverts my balance to 0. Refresh shows a balance of 0.

**Comment by Anaphase** [comment]
@sprice As discussed offline, I experienced the same bug I'm willing to bet it was because we both updated Ganache and reverted back to 1.1.0 the other day. Rebooting my computer fixed everything!

**Pull request merged**
